### ISSUE TITLE
RuntimeError: invalid argument 2: sizes do not match at /pytorch/torch/lib/THC/generated/../generic/THCTensorMasked.cu:13

### ISSUE THREAD

**Issue by JiyangZhang** [wanghm92/rw_fg#5]
Hi, interesting work and thanks for providing the code!
I cloned your code and try to train the model but got following error. I am not sure what is the course as there are few posts about this issue on google. Here is the exception:

> Loading train dataset from ../dataset/new_ncpcc/pt_data/newcc-trl/roto-newcc-trl.train.1.pt, number of examples: 5232
> rw_fg/model/onmt/modules/GlobalAttention.py:176: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
>   align_vectors = self.sm(align.view(batch*targetL, sourceL))
> rw_fg/model/onmt/modules/CopyGenerator.py:100: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
>   prob = F.softmax(logits)
> Traceback (most recent call last):
>   File "train.py", line 463, in <module>
>     main()
>   File "train.py", line 455, in main
>     train_model(model1, model2, fields, optim1, optim2, data_type, model_opt)
>   File "train.py", line 261, in train_model
>     train_stats, train_stats2 = trainer.train(train_iter, epoch, report_func)
>   File "rw_fg/model/onmt/Trainer.py", line 182, in train
>     report_stats, total_stats2, report_stats2, normalization)
>   File "rw_fg/model/onmt/Trainer.py", line 404, in _gradient_accumulation
>     self.model2((emb, trimmed_table_embs), tgt, src_lengths, dec_state)
>   File "lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
>     result = self.forward(*input, **kwargs)
>   File "rw_fg/model/onmt/Models.py", line 725, in forward
>     memory_lengths=lengths)
>   File "lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
>     result = self.forward(*input, **kwargs)
>   File "rw_fg/model/onmt/Models.py", line 337, in forward
>     tgt, (memory_bank, trimmed_table_embs), state, memory_lengths=memory_lengths)
>   File "w_fg/model/onmt/Models.py", line 621, in _run_forward_pass
>     memory_lengths=memory_lengths)
>   File "lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
>     result = self.forward(*input, **kwargs)
>   File "rw_fg/model/onmt/modules/GlobalAttention.py", line 173, in forward
>     align.data.masked_fill_(1 - mask, -float('inf'))
> RuntimeError: invalid argument 2: sizes do not match at /pytorch/torch/lib/THC/generated/../generic/THCTensorMasked.cu:13
> 

More details: 
* my environment:
pytorch==0.3.1
python==2.7
* command
I changed $BASE  in run.sh and run the script

Hope to hear from you soon,
Thanks!

**Comment by wanghm92** [comment]
You may want to start with printing out the dimensions of rnn_output and trimmed_table_embs at [line 619 of Models.py](https://github.com/wanghm92/rw_fg/blob/e3e96b9f43824f1c3627971ac4ef4f443dc0fe34/model/onmt/Models.py#L619) and see if they match.

**Comment by JiyangZhang** [comment]
It is weird that at one batch, the src length does not equal to the variable "lengths". Is it because the data is not aligned?

**Comment by JiyangZhang** [comment]
There is some bug in the data for model2 I think, after hiding the above error, another error occurs.

>  Traceback (most recent call last):
>   File "train.py", line 463, in <module>
>     main()
>   File "train.py", line 455, in main
>     train_model(model1, model2, fields, optim1, optim2, data_type, model_opt)
>   File "train.py", line 261, in train_model
>     train_stats, train_stats2 = trainer.train(train_iter, epoch, report_func)
>   File "rw_fg/model/onmt/Trainer.py", line 182, in train
>     report_stats, total_stats2, report_stats2, normalization)
>   File "rw_fg/model/onmt/Trainer.py", line 404, in _gradient_accumulation
>     self.model2((emb, trimmed_table_embs), tgt, src_lengths, dec_state)
>   File "python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
>     result = self.forward(*input, **kwargs)
>   File "rw_fg/model/onmt/Models.py", line 713, in forward
>     enc_final, memory_bank = self.encoder(src, lengths)
>   File "python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
>     result = self.forward(*input, **kwargs)
>   File "rw_fg/model/onmt/Models.py", line 156, in forward
>     packed_emb = pack(emb, lengths)
>   File "python2.7/site-packages/torch/nn/utils/rnn.py", line 74, in pack_padded_sequence
>     raise ValueError("lengths array has to be sorted in decreasing order")
> ValueError: lengths array has to be sorted in decreasing order
>

**Comment by wanghm92** [comment]
ValueError("lengths array has to be sorted in decreasing order") indicates that the sentences within a batch are not sorted by their lengths, which is a common runtime error, for [example](https://github.com/pytorch/pytorch/issues/8026). Unfortunately, [this flag](https://github.com/bentrevett/pytorch-sentiment-analysis/issues/37#issuecomment-493008858) is not available in pytorch 0.3.1, so you may want to add some code to sort the array.

**Comment by wanghm92** [comment]
> It is weird that at one batch, the src length does not equal to the variable "lengths". Is it because the data is not aligned?

The first error may be caused by this as well. I suggest you examine some sample data and see what's wrong with them.

**Comment by JiyangZhang** [comment]
That is weird, then how did run the model? I use the data and code from the repository.

Thank you very much.

**Comment by wanghm92** [comment]
I think everything is in the repo now. I had a hard time doing experiments working with this dataset, particularly the previous settings, e.g. using a torch(lua) based sequence tagger for evaluation. Although this project has reduced the complexity quite a bit, there are still a lot of steps to be followed carefully. Try adding some sorting to the input tensors

**Comment by wanghm92** [comment]
Sorting is already in place [here](https://github.com/wanghm92/rw_fg/blob/650a94908897dd940a246a82f0b67328a1272760/model/train.py#L176), so I  don't really know what's going on. Good luck!

**Comment by LucaDeGrandis** [comment]
Hi, I am facing the same problem. Did you solve it?
